name: Atualizar dados de famílias

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🟣 Configurar Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1'

      - name: 📦 Cache dos pacotes Julia
        uses: julia-actions/cache@v3

      - name: 📦 Instalar dependências
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

      - name: 🚀 Executar script de coleta
        run: julia --project=. Scripts/conect_reflora.jl

      - name: 📅 Definir data
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 📤 Fazer upload do arquivo como artifact
        uses: actions/upload-artifact@v4
        with:
          name: dados-flora-${{ env.TODAY }}
          path: dados_reflora.csv
          if-no-files-found: error
